version: '2'
services:
  web:
    build: 
      context: crowdfunding-api
    links:
      - db:db
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
      - ./crowdfunding-api/out:/opt/jboss/wildfly/standalone/deployments
  db:
    build:
      context: crowdfunding-persistence
