version: '2'
services:
  api:
    build: 
      context: crowdfunding-api
    links:
      - db:db
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
      - ./crowdfunding-api/out:/opt/jboss/wildfly/standalone/deployments
  db:
    build:
      context: crowdfunding-persistence
  http:
    image: httpd:2.4
    volumes:
      - ./crowdfunding-http/public:/usr/local/apache2/htdocs
    links:
      - api:api
    ports:
      - 8081:80